name: Update Wiseplay Playlist
on:
  schedule:
    - cron: '*/15 * * * *' # สั่งรันสคริปต์อัตโนมัติทุกๆ 15 นาที
  workflow_dispatch: # เปิดให้คุณกดสั่งรันเองแบบ Manual ได้ด้วย

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        
    - name: Install dependencies
      run: pip install requests
      
    - name: Run Script
      run: python update.py
      
    - name: Commit and Push changes
      run: |
        git config --global user.name "Automated Bot"
        git config --global user.email "bot@github.com"
        git add ATMFlix.w3u
        git commit -m "Auto updated token" || exit 0
        git pull --rebase origin main
        git push origin main
